name: Bug Report
description: File a bug report to help us improve GECS.
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Please fill out the following details.
  - type: input
    id: version
    attributes:
      label: GECS Version
      description: What version of GECS are you using?
      placeholder: ex. 1.2.0
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug and what you expected to happen.
      placeholder: Tell us what you saw...
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Tell us how to reproduce the issue.
      placeholder: |
        1. Create entity
        2. Add component
        3. Observe error
    validations:
      required: true
